from django.urls import path
from .views import (
    CreateUserView,
    PPPoEVerifyView,
    PackageListView,
    InitiatePaymentView,
    MpesaCallbackView,
    SessionStatusView,
    ActivateVoucherView,
    ReconnectView,
    DashboardStatsView,   
    RouterListView,        
    HotspotUserListView,
    SessionDestroyView, PackageDestroyView,
    PaymentListView, PaymentDestroyView,
    VoucherListView, VoucherDestroyView,
    RouterDestroyView, FreeTrialView,PPPoEPlanListView, PPPoEPlanDestroyView,
    IPPoolListView, IPPoolDestroyView,
    PPPoEClientListView, PPPoEClientDestroyView,
    PPPoEClientStatusView, PPPoERenewView, PPPoECallbackView,
    ResellerCreateView, ResellerListView, ResellerLoginView,
    ResellerProfileView, ResellerTopUpView, ResellerTopUpCallbackView,
    ResellerBuyVouchersView, ResellerVouchersView, ResellerTopUpHistoryView,
)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('register/',         CreateUserView.as_view(),       name='register'),
    path('login/',            TokenObtainPairView.as_view(),  name='login'),
    path('token/refresh/',    TokenRefreshView.as_view(),     name='refresh'),
    path('packages/',         PackageListView.as_view(),      name='packages'),
    path('pay/',              InitiatePaymentView.as_view(),  name='pay'),
    path('mpesa/callback/',   MpesaCallbackView.as_view(),    name='mpesa-callback'),
    path('session/<int:pk>/',   SessionStatusView.as_view(), name='session-status'),
    path('voucher/activate/',    ActivateVoucherView.as_view(),  name='voucher-activate'),
    path('reconnect/',        ReconnectView.as_view(),        name='reconnect'),
    path('dashboard/stats/',  DashboardStatsView.as_view(),   name='dashboard-stats'),
    path('routers/',          RouterListView.as_view(),        name='routers'),
    path('hotspot/users/',    HotspotUserListView.as_view(),   name='hotspot-users'),
    path('hotspot/users/<pk>/', SessionDestroyView.as_view()),
    path('packages/<pk>/',      PackageDestroyView.as_view()),
    path('payments/',           PaymentListView.as_view()),
    path('payments/<pk>/',      PaymentDestroyView.as_view()),
    path('vouchers/',           VoucherListView.as_view()),
    path('vouchers/<pk>/',      VoucherDestroyView.as_view()),
    path('routers/<pk>/',       RouterDestroyView.as_view()),
    path('free-trial/',      FreeTrialView.as_view(), name='free-trial'),
    path('pppoe/plans/',               PPPoEPlanListView.as_view()),
    path('pppoe/plans/<pk>/',          PPPoEPlanDestroyView.as_view()),
    path('pppoe/ip-pools/',            IPPoolListView.as_view()),
    path('pppoe/ip-pools/<pk>/',       IPPoolDestroyView.as_view()),
    path('pppoe/clients/',             PPPoEClientListView.as_view()),
    path('pppoe/clients/<pk>/',        PPPoEClientDestroyView.as_view()),
    path('pppoe/client/<str:username>/', PPPoEClientStatusView.as_view()),
    path('pppoe/renew/',               PPPoERenewView.as_view()),
    path('pppoe/callback/',            PPPoECallbackView.as_view()),
    path('pppoe/verify/',             PPPoEVerifyView.as_view()),
    path('reseller/login/',           ResellerLoginView.as_view()),
    path('reseller/register/',        ResellerCreateView.as_view()),
    path('reseller/list/',            ResellerListView.as_view()),
    path('reseller/profile/',         ResellerProfileView.as_view()),
    path('reseller/topup/',           ResellerTopUpView.as_view()),
    path('reseller/topup/callback/',  ResellerTopUpCallbackView.as_view()),
    path('reseller/buy-vouchers/',    ResellerBuyVouchersView.as_view()),
    path('reseller/vouchers/',        ResellerVouchersView.as_view()),
    path('reseller/topup/history/',   ResellerTopUpHistoryView.as_view()),
]