# Generated by Django 6.0.5 on 2026-05-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmjapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
